{
 "title": "Varken [v1.8.x]",
 "tags": [
  "Plex",
  "Tautulli",
  "Sonarr",
  "Radarr"
 ],
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "movieslibrary", "label": "Movies Library Name", "query": "Movies" },
   { "name": "tvlibrary", "label": "TV Library Name", "query": "TV Shows" }
  ]
 },
 "panels": [
  {
   "title": "Total BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "LAN BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "WAN BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "SELECT \"pending\" FROM \"Overseerr\" WHERE (\"type\" = 'Request_Counts') AND $timeFilter",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Req. Approved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "approved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Req. Completed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =~ /^$movieslibrary$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT sum(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =~ /^$tvlibrary$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Issues Pending",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "open" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues Resolved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "closed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added TV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Device Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_device_type",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_video_decision",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "query": "SELECT \"hash\" FROM \"Radarr\" WHERE (\"type\" = 'Queue') AND $timeFilter GROUP BY \"protocol_id\", \"name\"",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows on Today (Sonarr)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "query": "SELECT distinct(\"hash\") FROM \"Sonarr\" WHERE (\"type\" = 'Queue') AND $timeFilter GROUP BY \"protocol_id\", \"sxe\", \"name\"",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "titleSlug" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Server Popularity",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": ".",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Missing TV Episodes (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"friendly_name\",  \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"",
     "select": [
      [
       { "params": [ "session_key" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Overseerr Requests Pending",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "requested_date" ], "type": "tag" },
      { "params": [ "requested_user" ], "type": "tag" },
      { "params": [ "request_type" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "Overseerr",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "5" }
     ]
    }
   ]
  }
 ]
}