version: '3'

networks:
  internal:
    driver: bridge

services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - internal
    volumes:
      - /path/to/docker-influxdb/config-folder:/var/lib/influxdb
    restart: unless-stopped

  varken:
    hostname: varken
    container_name: varken
    image: ghcr.io/thezak48/varken:develop
    networks:
      - internal
    volumes:
      - /path/to/docker-varken/config-folder:/config
    environment:
      - TZ=Europe/London
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - /path/to/docker-grafana/config-folder:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - influxdb
      - varken
    restart: unless-stopped
