{
 "title": "Varken [v2.0.x]",
 "tags": [
  "Plex",
  "Tautulli",
  "Sonarr",
  "Radarr"
 ],
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "movieslibrary",
    "label": "Movies Library",
    "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"libraries\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"movie\")\r\n  |> keep(columns: [\"section_type\", \"_value\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")\r\n"
   },
   {
    "name": "tvlibrary",
    "label": "TV Library",
    "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"libraries\")\r\n  |> filter(fn: (r) => r[\"section_type\"] == \"show\")\r\n  |> keep(columns: [\"section_type\", \"_value\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Total BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"total_bandwidth\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "total_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "LAN BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"lan_bandwidth\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "WAN BW",
   "type": "stat",
   "description": "Streaming Brain Estimate",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"wan_bandwidth\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"pending\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Req. Approved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"approved\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "approved" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Req. Completed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"available\")\r\n  |> filter(fn: (r) => r.type == \"Request_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"total\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${movieslibrary:regex}/)\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"total\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${movieslibrary:regex}/)\r\n  |> distinct()\r\n  |> sum(column: \"_value\")\r\n  |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$movieslibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"total\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${tvlibrary:regex}/)\r\n  |> distinct()\r\n  |> sum(column: \"_value\")\r\n  |> keep(columns: [\"_value\"])",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"seasons\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${tvlibrary:regex}/)\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"episodes\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${tvlibrary:regex}/)\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"stream_count\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"transcode_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"direct_play_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"direct_streams\")\r\n  |> filter(fn: (r) => r.type == \"current_stream_stats\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Issues Pending",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"open\")\r\n  |> filter(fn: (r) => r.type == \"Issues_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "open" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Issues Resolved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"closed\")\r\n  |> filter(fn: (r) => r.type == \"Issues_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "closed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"total\")\r\n  |> filter(fn: (r) => r.type == \"Issues_Counts\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Issues_Counts" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added TV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"episodes\")\r\n  |> filter(fn: (r) => r.type == \"library_stats\")\r\n  |> filter(fn: (r) => r.section_name =~ /^${tvlibrary:regex}/)\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=~", "value": "/^$tvlibrary$/" }
     ]
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"latitude\", \"longitude\", \"full_location\", \"name\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"latitude\", \"longitude\", \"full_location\", \"name\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Device Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_device_type",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Tautulli\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"device_type\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"device_type\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_video_decision",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"video_decision\"], mode: \"by\")\r\n  |> distinct()\r\n  |> count()\r\n  |> keep(columns: [\"_time\", \"_value\", \"video_decision\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Radarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Queue\")\r\n  |> group(columns: [\"name\", \"protocol_id\", \"quality\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"name\", \"protocol_id\", \"quality\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows on Today (Sonarr)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "downloaded" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Future\")\r\n  |> group(columns: [\"downloaded\", \"name\", \"sxe\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"downloaded\", \"name\", \"sxe\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Future" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol_id" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Queue\")\r\n  |> group(columns: [\"protocol_id\", \"sxe\", \"name\", \"quality\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"protocol_id\", \"sxe\", \"name\", \"quality\"])\r\n  |> sort(columns: [\"_time\"])\r\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "titleSlug" ], "type": "tag" }
     ],
     "measurement": "Radarr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Radarr\")\r\n  |> filter(fn: (r) => r[\"Missing_Available\"] == \"0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hash\")\r\n  |> group(columns: [\"name\", \"titleSlug\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Session\")\r\n  |> group(columns: [\"friendly_name\", \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"friendly_name\", \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "session_key" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Missing TV Episodes (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "sxe" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Sonarr\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"Missing\")\r\n  |> group(columns: [\"server\", \"sxe\", \"name\"])\r\n  |> distinct()\r\n  |> yield(name: \"distinct\")",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "title": "Overseerr Requests Pending",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "requested_date" ], "type": "tag" },
      { "params": [ "requested_user" ], "type": "tag" },
      { "params": [ "request_type" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "Overseerr",
     "query": "from(bucket: \"varken\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._field == \"hash\")\r\n  |> filter(fn: (r) => r.type == \"Requests\")\r\n  |> filter(fn: (r) => r.status != 0)\r\n  |> filter(fn: (r) => r.status != 2)\r\n  |> group(columns: [\"title\", \"requested_date\", \"requested_user\", \"request_type\", \"status\"], mode: \"by\")\r\n  |> distinct()\r\n  |> keep(columns: [\"_time\", \"_value\", \"title\", \"requested_date\", \"requested_user\", \"request_type\", \"status\"])\r\n  |> sort(columns: [\"_time\"])",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Requests" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "5" }
     ]
    }
   ]
  }
 ]
}